### ISSUE TITLE
Use Response Policy Zone?

### ISSUE THREAD

**Issue by daspri** [mueller-ma/block-ads-via-dns#1]
Can this script use bind's RPZ to shorten the list of blocked domains and lessen the number of open files?  

Like in this example:
http://unix.stackexchange.com/questions/253841/large-zone-file-for-bind9-ad-blocking

I believe the RPZ feature is for ad blocking:
http://www.zytrax.com/books/dns/ch9/rpz.html

**Comment by mueller-ma** [comment]
I will have a closer look to this feature. Do you have any perfomance issues with my configurations?

**Comment by daspri** [comment]
> Limitations
>     The db.blocked will cause some errors on bind start

I wanted to fix the log startup errors and slow loading.  Maybe performance will be better with larger lists but I do not have measurements.   I have made the adjustments to my configuration based on rpz examples.  You can measure the difference if you are interested.

Add one line to options section of named.conf: 
`response-policy { zone "rpz" policy nxdomain; } qname-wait-recurse no;`

Add the zone:
```
zone "rpz" {
  type master;
  notify no;
  file "rpz.zone";
};
```
rpz.zone file:
```
$TTL 1D
@ 1D  IN SOA myserver.localdomain.local. hostmaster 36 8H 2H 1W 2H
@ IN NS myserver.localdomain.local.

$INCLUDE rpz.blocked.db
```

rpz.blocked.db example:
`adsite.doubleclick.net CNAME .`

If you prefer to return 0.0.0.0 instead of NXDOMAIN remove the "policy nxdomain" from the option line above and do the following, but hosts that contain an underscore will cause errors with "A 0.0.0.0"

rpz.blocked.db example2:
```
adsite.doubleclick.net A 0.0.0.0
ad_site.doubleclick.net CNAME .
```

**Comment by mueller-ma** [comment]
I have updated README.md and included a new db.blocked file. This won't cause errors on startup.
Bind starts on my VM in 8 seconds
